/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finantial;

import DBConnection.DBConnection;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import login.Login;
import login.LoginUser;

/**
 *
 * @author NTC
 */
public class Finantial extends javax.swing.JFrame {
     private LoginUser finantialUser;
     private static final String MALE = "Male";
     private static final String FEMALE = "Female";
     
     private String patientSsn = "";
    /**
     * Creates new form Finantial
     */
    public Finantial(LoginUser finantialName) {
        this.finantialUser = finantialName;
        initComponents();
        this.setResizable(false);
        addfinantialInfoToGUI();
        addChangePasswordDefaultSettings();
        
    }
    
    public LoginUser getfinantialUser() {
        return finantialUser;
    }

    public void setAdminUser(LoginUser adminUser) {
        this.finantialUser = finantialUser;
    }
    
    private void addfinantialInfoToGUI() {
        jLabel1.setText(finantialUser.getUsername());
        jTextField1.setText(finantialUser.getUsername());
        jTextField2.setText(finantialUser.getSsn());
        jTextField3.setText(finantialUser.getEmail());
        jDateChooser1.setDate(finantialUser.getBirthdate());
        if (finantialUser.getGender().equalsIgnoreCase(MALE)) {
            jRadioButton1.setSelected(true);
        } else if (finantialUser.getGender().equalsIgnoreCase(FEMALE)) {
            jRadioButton2.setSelected(true);
        }
        setEditProfileInfoUsernameDefault();
        setEditProfileInfoEmailDefault();
        setEditProfileInfoDateDefault();
    }
    
    public void addPlaceholder(JTextField text) {
        Font font = text.getFont();
        font = font.deriveFont(Font.BOLD);
        text.setFont(font);
        text.setForeground(Color.GRAY);
    }

    public void removePlaceholder(JTextField text) {
        Font font = text.getFont();
        font = font.deriveFont(Font.PLAIN | Font.BOLD);
        text.setFont(font);
        text.setForeground(Color.BLACK);
    }
    
     private void addChangePasswordDefaultSettings() {
        this.setFocusable(true);
        addPlaceholder(jPasswordField1);
        addPlaceholder(jPasswordField2);
        addPlaceholder(jPasswordField3);
        setDefaultChangePasswordGUIValues();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField3 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/username.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-money-100.png"))); // NOI18N
        jLabel2.setText(" Pay");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 160, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/settings_icon.png"))); // NOI18N
        jLabel3.setText("Settings");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 150, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        jLabel4.setText("LogOut");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 160, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 650));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 84, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 750, 777, -1));

        jPanel11.setBackground(new java.awt.Color(255, 255, 204));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/finantial.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 204));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-user.png"))); // NOI18N
        jLabel6.setText("   ProfileInfo");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/password-100.png"))); // NOI18N
        jLabel7.setText("ChangePassword");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 204));

        jLabel8.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36)); // NOI18N
        jLabel8.setText("ChangePassword");

        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusLost(evt);
            }
        });
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jPasswordField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField2FocusLost(evt);
            }
        });

        jPasswordField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField3FocusLost(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("Change Password");
        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 255)));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("         Cancel");
        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 255)));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPasswordField1)
                            .addComponent(jPasswordField2)
                            .addComponent(jPasswordField3)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addGap(32, 32, 32)
                .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addGap(31, 31, 31)
                .addComponent(jPasswordField3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addGap(82, 82, 82)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab3", jPanel7);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        jButton1.setText("Pay");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 139, 50));

        jTextField4.setToolTipText("");
        jPanel9.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 220, 50));
        jPanel9.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 220, 20));

        jTextField5.setEditable(false);
        jPanel9.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 220, 50));

        jButton2.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        jButton2.setText("Check");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 140, 50));

        jLabel21.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        jLabel21.setText("Cancel");
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel9.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 490, 120, 50));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/happy-wallet.jpg"))); // NOI18N
        jPanel9.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 640));

        jTabbedPane1.addTab("tab5", jPanel9);

        jPanel8.setBackground(new java.awt.Color(255, 255, 204));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setText("Username");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 164, 48));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setText("SSN");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 164, 40));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setText("Email");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 164, 40));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setText("Gender");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 164, 40));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setText("Birthdate");
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 164, -1));

        jTextField1.setEditable(false);
        jPanel8.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 100, 361, 41));

        jTextField2.setEditable(false);
        jPanel8.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 194, 365, 40));

        jTextField3.setEditable(false);
        jPanel8.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 288, 365, 40));

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 204));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 0, 0));
        jRadioButton1.setText("Male");
        jRadioButton1.setOpaque(true);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel8.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 384, -1, -1));

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 204));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 0, 0));
        jRadioButton2.setText("Female");
        jRadioButton2.setOpaque(true);
        jPanel8.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 384, -1, -1));
        jPanel8.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 428, 365, 40));

        jLabel17.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        jLabel17.setText("   Save");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel17MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel17MouseExited(evt);
            }
        });
        jPanel8.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 516, 150, 45));

        jLabel18.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        jLabel18.setText("  Cancel");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel18MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel18MouseExited(evt);
            }
        });
        jPanel8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 516, 150, 45));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit2.png"))); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, 93, 55, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit2.png"))); // NOI18N
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 283, 55, 41));
        jPanel8.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 169, 280, -1));
        jPanel8.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 420, 280, -1));
        jPanel8.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 561, 9, -1));
        jPanel8.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 480, 365, -1));
        jPanel8.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 334, 365, -1));
        jPanel8.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 147, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profileInfo.png"))); // NOI18N
        jLabel11.setText("Account Info");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 236, 68));

        jTabbedPane1.addTab("tab4", jPanel8);

        jPanel11.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, -1, 670));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);
        jPanel11.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 50));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, 630));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 938, 634));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
                        addfinantialInfoToGUI();

         jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
                        addChangePasswordDefaultSettings();
         jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
         jTabbedPane1.setSelectedIndex(1);
         setDefaultChangePasswordGUIValues();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
         jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked
     private void setDefaultChangePasswordGUIValues() {
        setDefaultOldPassGUIValue();
        setDefaultNewPassGUIValue();
        setDefaultConfirmNewPassGUIValues();
        oldPasswordFieldsLostFocus();
        newPasswordFieldsLostFocus();
        confirmNewPasswordFieldsLostFocus();
    }
     
    private void setDefaultOldPassGUIValue() {
        jPasswordField1.setBorder(null);
        jLabel23.setText("");
    }

    private void setDefaultNewPassGUIValue() {
        jPasswordField2.setBorder(null);
        jLabel24.setText("");
    } 
    
    private void setDefaultConfirmNewPassGUIValues() {
        jPasswordField3.setBorder(null);
        jLabel25.setText("");
    }
    
     private void oldPasswordFieldGainFocus() {
        jPasswordField1.setText(null);
        jPasswordField1.requestFocus();
        jPasswordField1.setEchoChar('*');
        removePlaceholder(jPasswordField1);
    }

    private void newPasswordFieldGainFocus() {
        jPasswordField2.setText(null);
        jPasswordField2.requestFocus();
        jPasswordField2.setEchoChar('*');
        removePlaceholder(jPasswordField2);
    }
    
    private void confirmNewPasswordFieldGainFocus() {
        jPasswordField3.setText(null);
        jPasswordField3.requestFocus();
        jPasswordField3.setEchoChar('*');
        removePlaceholder(jPasswordField3);
    }
    
    private void oldPasswordFieldsLostFocus() {
        addPlaceholder(jPasswordField1);
        jPasswordField1.setText("Old Password");
        jPasswordField1.setEchoChar((char) 0);
    }

    private void newPasswordFieldsLostFocus() {
        addPlaceholder(jPasswordField2);
        jPasswordField2.setText("New Password");
        jPasswordField2.setEchoChar((char) 0);
    }

    private void confirmNewPasswordFieldsLostFocus() {
        addPlaceholder( jPasswordField3);
         jPasswordField3.setText("Confirm New Password");
         jPasswordField3.setEchoChar((char) 0);
    }
    
    private void setEditProfileInfoUsernameDefault() {
        jTextField1.setBorder(null);
        jLabel31.setText("");
    }

    private void setEditProfileInfoEmailDefault() {
        jTextField3.setBorder(null);
        jLabel30.setText("");
    }

    private void setEditProfileInfoDateDefault() {
        jDateChooser1.setBorder(null);
        jLabel29.setText("");
    }

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        jTextField4.setText("");
        jTextField4.setBorder(null);
        patientSsn="";
        jTextField5.setText("");
        jButton1.setEnabled(false);
        jLabel32.setText("");
         jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jPasswordField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField3FocusLost
        // TODO add your handling code here:
         if (jPasswordField3.getText().length() == 0) {
            confirmNewPasswordFieldsLostFocus();
        }
    }//GEN-LAST:event_jPasswordField3FocusLost

    private void jPasswordField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField3FocusGained
        // TODO add your handling code here:
         if (jPasswordField3.getText().equals("Confirm New Password")) {
            confirmNewPasswordFieldGainFocus();
        }
    }//GEN-LAST:event_jPasswordField3FocusGained

    private void jPasswordField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField2FocusLost
        // TODO add your handling code here:
         if (jPasswordField2.getText().length() == 0) {
            newPasswordFieldsLostFocus();
        }
    }//GEN-LAST:event_jPasswordField2FocusLost

    private void jPasswordField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField2FocusGained
        // TODO add your handling code here:
        if (jPasswordField2.getText().equals("New Password")) {
            newPasswordFieldGainFocus();
        }

    }//GEN-LAST:event_jPasswordField2FocusGained

    private void jPasswordField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusLost
        // TODO add your handling code here:
         if (jPasswordField1.getText().length() == 0) {
            oldPasswordFieldsLostFocus();
        }
    }//GEN-LAST:event_jPasswordField1FocusLost

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusGained
        // TODO add your handling code here:
        if (jPasswordField1.getText().equals("Old Password")) {
            oldPasswordFieldGainFocus();
        }
    }//GEN-LAST:event_jPasswordField1FocusGained

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        // TODO add your handling code here:
       jLabel10.setBackground(new Color(0, 153, 102));
       jLabel10.setForeground(Color.WHITE);
               
    }//GEN-LAST:event_jLabel10MouseExited

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        // TODO add your handling code here:
         jLabel10.setBackground(Color.WHITE);
        jLabel10.setForeground(new Color(0, 153, 102));
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        // TODO add your handling code here:
       jLabel9 .setBackground(new Color(0, 153, 102));
        jLabel9 .setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        // TODO add your handling code here:
          jLabel9 .setBackground(Color.WHITE);
        jLabel9 .setForeground(new Color(0, 153, 102));
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
         String oldPassword = jPasswordField1.getText();
        String newPassword = jPasswordField2.getText();
        String confirmNewPassword = jPasswordField3.getText();
        boolean isEmptyInputPassword = false;
        if (oldPassword.isEmpty() || jPasswordField1.getForeground().equals(Color.gray)) {
            jPasswordField1.setBorder(BorderFactory.createLineBorder(Color.RED, 3));
           jLabel23.setText("Old password cannot be empty");
            isEmptyInputPassword = true;
        } else {
            setDefaultOldPassGUIValue();
        }
        if (newPassword.isEmpty()||jPasswordField2.getForeground().equals(Color.gray)) {
            jPasswordField2.setBorder(BorderFactory.createLineBorder(Color.RED, 3));
            jLabel24.setText("New password cannot be empty");
            isEmptyInputPassword = true;
        } else {
            setDefaultNewPassGUIValue();
        }
        if (confirmNewPassword.isEmpty()||jPasswordField3.getForeground().equals(Color.gray)) {
            jPasswordField3.setBorder(BorderFactory.createLineBorder(Color.RED, 3));
            jLabel25.setText("Confirm new password cannot be empty");
            isEmptyInputPassword = true;
        } else {
            setDefaultConfirmNewPassGUIValues();
        }
        if (!isEmptyInputPassword) {
            if (!oldPassword.equals(finantialUser.getPassword())) {
                jPasswordField1.setBorder(BorderFactory.createLineBorder(Color.RED, 3));
                jLabel23.setText("Old password is incorrect");
            } else if (newPassword.length() < 6) {
                jPasswordField2.setBorder(BorderFactory.createLineBorder(Color.RED, 3));
                jLabel24.setText("Password cannot be less than 8 characters");
            } else if (!newPassword.equals(confirmNewPassword)) {
                jPasswordField3.setBorder(BorderFactory.createLineBorder(Color.RED, 3));
                jLabel25.setText("Confirm new password should equal new password");
            } else {
                try {
                    int okNoChangePassResult = JOptionPane.showConfirmDialog(this, "Are you sure to change password",
                            "Confirm changing password", JOptionPane.YES_NO_OPTION);
                    if (okNoChangePassResult == JOptionPane.YES_OPTION) {
                        String updateQuery = "UPDATE hospital.login SET apassword = '" + newPassword + "' where ssn = '" + finantialUser.getSsn() + "'";
                        Connection db = DBConnection.getDBConnection();
                        PreparedStatement p = db.prepareStatement(updateQuery);
                        p.executeUpdate();
                        finantialUser.setPassword(newPassword);
                        setDefaultChangePasswordGUIValues();
                        JOptionPane.showMessageDialog(this, "Changing password done successfully!");
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Error in change password");
                }
            }
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
         jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here:
        boolean isEmailEditable = !jTextField3.isEditable();
        jLabel17.setEnabled(!(jTextField1.isEditable() || isEmailEditable));
        jTextField3.setEditable(isEmailEditable);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource(isEmailEditable ? "/images/done1.png" : "/images/edit2.png")));
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
        boolean isUsernameEditable = !jTextField1.isEditable();
        jLabel17.setEnabled(!(isUsernameEditable || jTextField3.isEditable()));
        jTextField1.setEditable(isUsernameEditable);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource(isUsernameEditable ? "/images/done1.png" : "/images/edit2.png")));
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseExited
        // TODO add your handling code here:
        jLabel18.setBackground(new Color(153, 204, 255));
    }//GEN-LAST:event_jLabel18MouseExited

    private void jLabel18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseEntered
        // TODO add your handling code here:
        jLabel18.setBackground(Color.GRAY);
    }//GEN-LAST:event_jLabel18MouseEntered

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
        addfinantialInfoToGUI();
        setEditProfileInfoUsernameDefault();
        setEditProfileInfoEmailDefault();
        setEditProfileInfoDateDefault();
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseExited
        // TODO add your handling code here:
        jLabel17.setBackground(new Color(153, 204, 255));
    }//GEN-LAST:event_jLabel17MouseExited

    private void jLabel17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseEntered
        // TODO add your handling code here:
        if (jLabel17.isEnabled()) {
            jLabel17.setBackground(Color.GRAY);
        }
    }//GEN-LAST:event_jLabel17MouseEntered

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            if (jLabel17.isEnabled()){
            java.util.Date date =  jDateChooser1.getDate();
            String gender = jRadioButton1.isSelected() ? MALE : jRadioButton2.isSelected() ? FEMALE : "";
            String username = jTextField1.getText();
            String email = jTextField3.getText();

            if (username.isEmpty()) {
                jTextField1.setBorder(BorderFactory.createLineBorder(Color.RED, 3));
                jLabel31.setText("Username cannot be empty");
            } else {
                setEditProfileInfoUsernameDefault();
            }
            if (email.isEmpty()) {
                jTextField3.setBorder(BorderFactory.createLineBorder(Color.RED, 3));
                jLabel30.setText("Email cannot be empty");
            } else {
                setEditProfileInfoEmailDefault();
            }
            if (date == null) {
                jDateChooser1.setBorder(BorderFactory.createLineBorder(Color.RED, 3));
                jLabel29.setText("Date cannot be empty");
            } else {
                setEditProfileInfoDateDefault();
            }
            if (!username.isEmpty() && !email.isEmpty() && date != null) {

                java.sql.Date dateSql = new java.sql.Date(date.getYear(), date.getMonth(), date.getDate());
                String updateQuery = "UPDATE hospital.login SET uname = '" + username
                + "' ,email = '" + email + "' ,birthdate = '"
                + dateSql + "' ,gender = '" + gender
                + "' where ssn = '" + finantialUser.getSsn() + "'";
                // register the connection
                Connection c = DBConnection.getDBConnection();
                PreparedStatement p = c.prepareStatement(updateQuery);
                p.executeUpdate();
                
               updateQuery = "UPDATE hospital.staff SET birthdate = '" + dateSql
                               +"' ,email = '" + email
                                + "' ,username = '" + username
                                + "' where essnstaff = '" + finantialUser.getSsn() + "'";
                        // register the connection
                p = c.prepareStatement(updateQuery);
                p.executeUpdate();

                finantialUser.setUsername(username);
                finantialUser.setEmail(email);
                finantialUser.setBirthdate(dateSql);
                finantialUser.setGender(gender);
                jLabel1.setText(finantialUser.getUsername());

                JOptionPane.showMessageDialog(this, "Account Info updated successfully");
            }}

            //      try( PreparedStatement preparedStatement = db.prepareStatement(updateQuery)){
                //
                //
                //    preparedStatement.setString(1, name); // Set new value for uname
                //    preparedStatement.setString(2, email); // Set new value for email
                //    preparedStatement.setDate(3, (java.sql.Date) birthdate); // Set new value for birthdate (assuming newBirthdate is a java.sql.Date)
                //    preparedStatement.setString(4, ssn); // Set the SSN value for WHERE clause
                //    int rowsAffected = preparedStatement.executeUpdate();
                //    JOptionPane.showMessageDialog(null, "done");
                //
                //      }catch(SQLException e){
                //       e.printStackTrace();
                //      }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: update account info failed");
        }
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        patientSsn = jTextField4.getText();
        jTextField5.setText("");
        jButton1.setEnabled(false);
        int cost = 0;
        if (patientSsn.isEmpty()){
           jTextField4.setBorder(BorderFactory.createLineBorder(Color.RED, 3));
                 jLabel32.setText("ssn cannot be empty");
       }
        else {
                jTextField4.setBorder(null);
                 jLabel32.setText("");  
        }
        if (!patientSsn.isEmpty()){
            try {
                String query = "SELECT cost FROM hospital.history WHERE patientssn='" + patientSsn +"'AND  payornot='false'";
                Connection c = DBConnection.getDBConnection();
                PreparedStatement p = c.prepareStatement(query);
                ResultSet rs = p.executeQuery();
                if (!rs.next()){
                    query = "SELECT cost FROM hospital.history WHERE patientssn='" + patientSsn+"'";
                    p = c.prepareStatement(query);
                    rs = p.executeQuery();
                    if (!rs.next()){
                    JOptionPane.showMessageDialog(this, "Patient with ssn "+ patientSsn +" doesn't exist or doesn't have history");}
                    else {jTextField5.setText(""+cost);}
                }
                else {
                   do {
                    cost += rs.getInt("cost");
                } while (rs.next());
                
                  jTextField5.setText(""+cost);
                if (cost!=0){
                    jButton1.setEnabled(true);
                }
                }
             } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error in read patient history");
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try {
             
             int okNoChangePassResult = JOptionPane.showConfirmDialog(this, "Did you recieve "+ jTextField5.getText() + 
                     " from the patient "+ patientSsn,"Payment", JOptionPane.YES_NO_OPTION);
                    if (okNoChangePassResult == JOptionPane.YES_OPTION) {
             String updateQuery = "UPDATE hospital.history SET payornot = 'true'" +
                     " where patientssn = '" + patientSsn + "'";
             // register the connection
             Connection c = DBConnection.getDBConnection();
             PreparedStatement p = c.prepareStatement(updateQuery);
             p.executeUpdate();
                    JOptionPane.showMessageDialog(this, "The patient " + patientSsn +" paid successfully");
                    jButton1.setEnabled(false);
                    jTextField5.setText("0");
                    }
         } catch (Exception ex) {
              JOptionPane.showMessageDialog(this, "Error in Payment");
                System.out.println(ex);
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
